### ISSUE TITLE
Dev branch build is broken

### ISSUE THREAD

**Issue by briansull** [aspnet/JitBench#55]
I see that the build is currently  flagged as being broken, but there is no issue or content in PR that explains what the current build break looks like, so I am adding this issue.

I am building a standalone version  using "-r win10-x64"
I get two compilation errors:

```
D:\fxkit\JitBench\src\MusicStore>dotnet publish -r win10-x64 -o pubdir
Microsoft (R) Build Engine version 15.3.246.41955 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Models\MusicStoreContext.cs(7,36): error CS0246: The type or namespace name 'IdentityUser' could not be found (are you missing a using directive or an assembly reference?) [D:\fxkit\JitBench\src\MusicStore\MusicStore.csproj]
Models\MusicStoreContext.cs(9,18): error CS0311: The type 'MusicStore.Models.ApplicationUser' cannot be used as type parameter 'TUser' in the generic type or method 'IdentityDbContext<TUser>'. There is no implicit reference conversion from 'MusicStore.Models.ApplicationUser' to 'Microsoft.AspNetCore.Identity.IdentityUser'. [D:\fxkit\JitBench\src\MusicStore\MusicStore.csproj]
```

**Comment by rynowak** [comment]
This looks like another ASP.NET breaking change, I'll fix it. I'm working on getting the `dev` and `rel/...` branches added to our CI so I can be notified about these things

If you want something stable, I'd recommend the `rel/2.0.0-preview1` branch which uses a fixed set of ASP.NET libraries and the latest `dotnet` CLI/SDK/Runtime

**Comment by rynowak** [comment]
Looks like I missed the change to `MusicStoreContext` in https://github.com/aspnet/MusicStore/commit/6c13465dc2018b59eef2edd93c7f6a39e8ec14a1

I looked over this commit when I saw it get merged to the MusicStore repo, and didn't catch this in with all of the changes that aren't relevant to JitBench.

**Comment by briansull** [comment]
It sounds like you will be checking a fix for this shortly.
I rather continue working in the Dev branch as I need to collect profile data to use with future versions.

**Comment by rynowak** [comment]
`rel/2.0.0-preview1` works with the latest dotnet versions, do you mean you're tracking the ASP.NET changes specifically?

**Comment by rynowak** [comment]
Fixed here: 94040906c1a7d8b2db373d63dc97910781e27eb3

**Comment by briansull** [comment]
@rynowak Reopen

**Comment by rynowak** [comment]
??? Are you saying this is still broken?

This is passing on travis and appveyor
https://travis-ci.org/aspnet/JitBench/builds/238178713
https://ci.appveyor.com/project/aspnetci/jitbench/build/1.0.71

**Comment by briansull** [comment]
Yes, I was still getting those same two errors when building in the dev branch.
I sounded like you checked on something to the wrong branch and then reverted it.

**Comment by rynowak** [comment]
I checked it in to master and then reverted it there because master tracks 2.0.0-preview1.

The commit in dev is this one https://github.com/aspnet/JitBench/commit/94040906c1a7d8b2db373d63dc97910781e27eb3

**Comment by rynowak** [comment]
If you're still having trouble I can stop by and take a look. This is working for me and in on the CIs.

**Comment by briansull** [comment]
OK It is fixed, I had a local change that was prevent me from pulling down your fix.

**Comment by rynowak** [comment]
OK good, glad we got to the bottom of this.
